# Generated by Django 2.2.2 on 2019-06-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleProtocol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msid", models.PositiveIntegerField()),
                ("protocol_sequencing_number", models.CharField(max_length=25)),
                ("protocol_title", models.CharField(max_length=250)),
                ("is_protocol", models.BooleanField()),
                ("protocol_status", models.BooleanField()),
                ("uri", models.URLField()),
                ("datetime_record_created", models.DateTimeField()),
                ("datetime_record_updated", models.DateTimeField()),
            ],
        )
    ]
