# Generated by Django 2.2.2 on 2019-07-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bp", "0002_auto_20190624_0522")]

    operations = [
        migrations.AlterField(
            model_name="articleprotocol",
            name="protocol_title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="articleprotocol",
            name="uri",
            field=models.URLField(blank=True, null=True),
        ),
    ]
