# Generated by Django 2.2.16 on 2020-10-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0003_auto_20190717_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleprotocol',
            name='msid',
            field=models.BigIntegerField(),
        ),
    ]
